config/routes.rb
Rails.application.routes.draw do

resources :moussaillons

root"moussaillon#index"

get "moussaillon/new"

get "moussaillon/edit"

get "moussaillon/show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/moussaillons_controller.rb
class MoussaillonsController < ApplicationController
	def index 
	end

	def new
		@moussaillon= Moussaillon.new
	end

def create
  @moussaillon = Moussaillon.create(moussaillon_params)
  	if @moussaillon.save
  		redirect_to @moussaillon
  	else 
  		render 'new'
end 
end

  def edit 
    @moussaillon = Moussaillon.find(params[:id])
  end

  def update 
    @gmoussaillon = Moussaillon.find(params[:id])
    if @Moussaillon.update(moussaillon_params)
      redirect_to @moussaillon
      else 
      render 'edit'
 end
end


def show
  @moussaillon = Moussaillon.find(params[:id])
end

private
   def moussaillon_params
   params.permit(:bio, :username, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moussaillons_helper.rb
module MoussaillonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moussaillons/edit.html.erb
<h1> Balances ta bio  </h1>


<%= form_tag moussaillon_path(@moussaillon) do %>
    <%= label_tag 'bio' %>
    <%= text_field_tag 'bio' %>
    <%= submit_tag "Poster ta bio"%>
<% end %>

app/views/moussaillons/new.html.erb
<h1> Hello petit moussaillon!! </h1>

<h1> Creer un profil</h1>
<%= form_tag (moussaillons_path) do %>
<%= label_tag 'username', 'username' %>
    <%= text_field_tag 'username' %>
    <%= label_tag 'email', 'email' %>
    <%= text_field_tag 'email' %>
    <%= submit_tag "Creer un profil"%>
<% end %>

app/views/moussaillons/show.html.erb
<p>
  <strong>Bienvenue</strong><br/>
  <%= @moussaillon.username %>
</p>
 
<p>

    <a href="<%= edit_moussaillon_path(@moussaillon.id) %>" >balances</a>

</p>